#!/usr/bin/env bash
set -euo pipefail

echo "Running PHPStan..."
XDEBUG_MODE=off php -d memory_limit=1G vendor/bin/phpstan analyse

echo "Running unit tests..."
XDEBUG_MODE=off vendor/bin/pest --testsuite=Unit

echo "Running feature tests..."
XDEBUG_MODE=off php artisan test --testsuite=Feature

